# Generated by Django 2.1.2 on 2018-10-07 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectCentricMail', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectClassify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Spam', models.BooleanField()),
                ('Formal', models.BooleanField()),
                ('Project', models.CharField(max_length=32)),
                ('m_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjectCentricMail.MessageInfo')),
            ],
        ),
    ]
