# Generated by Django 2.0.7 on 2018-10-08 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectCentricMail', '0002_projectclassify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectclassify',
            name='Formal',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='projectclassify',
            name='Spam',
            field=models.NullBooleanField(),
        ),
    ]
